/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePlayerInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePlayerInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePlayerInput
        //private CreatePlayerInput instance;

        public CreatePlayerInputTests()
        {
            // TODO uncomment below to create an instance of CreatePlayerInput
            //instance = new CreatePlayerInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePlayerInput
        /// </summary>
        [Fact]
        public void CreatePlayerInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePlayerInput
            //Assert.IsType<CreatePlayerInput>(instance);
        }


        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Fact]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'GameId'
        /// </summary>
        [Fact]
        public void GameIdTest()
        {
            // TODO unit test for the property 'GameId'
        }
        /// <summary>
        /// Test the property 'IsCreateWallet'
        /// </summary>
        [Fact]
        public void IsCreateWalletTest()
        {
            // TODO unit test for the property 'IsCreateWallet'
        }
        /// <summary>
        /// Test the property 'CustomProps'
        /// </summary>
        [Fact]
        public void CustomPropsTest()
        {
            // TODO unit test for the property 'CustomProps'
        }

    }

}
