/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MintBatchInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MintBatchInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MintBatchInput
        //private MintBatchInput instance;

        public MintBatchInputTests()
        {
            // TODO uncomment below to create an instance of MintBatchInput
            //instance = new MintBatchInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MintBatchInput
        /// </summary>
        [Fact]
        public void MintBatchInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" MintBatchInput
            //Assert.IsType<MintBatchInput>(instance);
        }


        /// <summary>
        /// Test the property 'GameId'
        /// </summary>
        [Fact]
        public void GameIdTest()
        {
            // TODO unit test for the property 'GameId'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'PlayerAddress'
        /// </summary>
        [Fact]
        public void PlayerAddressTest()
        {
            // TODO unit test for the property 'PlayerAddress'
        }
        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Fact]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }
        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

    }

}
