/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        public ProjectTests()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Fact]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" Project
            //Assert.IsType<Project>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'LogoImage'
        /// </summary>
        [Fact]
        public void LogoImageTest()
        {
            // TODO unit test for the property 'LogoImage'
        }
        /// <summary>
        /// Test the property 'Medias'
        /// </summary>
        [Fact]
        public void MediasTest()
        {
            // TODO unit test for the property 'Medias'
        }
        /// <summary>
        /// Test the property 'SocialLinks'
        /// </summary>
        [Fact]
        public void SocialLinksTest()
        {
            // TODO unit test for the property 'SocialLinks'
        }
        /// <summary>
        /// Test the property 'MainMedia'
        /// </summary>
        [Fact]
        public void MainMediaTest()
        {
            // TODO unit test for the property 'MainMedia'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'WebLink'
        /// </summary>
        [Fact]
        public void WebLinkTest()
        {
            // TODO unit test for the property 'WebLink'
        }
        /// <summary>
        /// Test the property 'Discord'
        /// </summary>
        [Fact]
        public void DiscordTest()
        {
            // TODO unit test for the property 'Discord'
        }
        /// <summary>
        /// Test the property 'Twitter'
        /// </summary>
        [Fact]
        public void TwitterTest()
        {
            // TODO unit test for the property 'Twitter'
        }
        /// <summary>
        /// Test the property 'Instagram'
        /// </summary>
        [Fact]
        public void InstagramTest()
        {
            // TODO unit test for the property 'Instagram'
        }
        /// <summary>
        /// Test the property 'ContactPhone'
        /// </summary>
        [Fact]
        public void ContactPhoneTest()
        {
            // TODO unit test for the property 'ContactPhone'
        }
        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Fact]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Fact]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Fact]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }

    }

}
