/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SetSaleStatusDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetSaleStatusDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetSaleStatusDto
        //private SetSaleStatusDto instance;

        public SetSaleStatusDtoTests()
        {
            // TODO uncomment below to create an instance of SetSaleStatusDto
            //instance = new SetSaleStatusDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetSaleStatusDto
        /// </summary>
        [Fact]
        public void SetSaleStatusDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetSaleStatusDto
            //Assert.IsType<SetSaleStatusDto>(instance);
        }


        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'SaleStatus'
        /// </summary>
        [Fact]
        public void SaleStatusTest()
        {
            // TODO unit test for the property 'SaleStatus'
        }

    }

}
