/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TokenInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenInput
        //private TokenInput instance;

        public TokenInputTests()
        {
            // TODO uncomment below to create an instance of TokenInput
            //instance = new TokenInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenInput
        /// </summary>
        [Fact]
        public void TokenInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenInput
            //Assert.IsType<TokenInput>(instance);
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
