/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        public TransactionTests()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Fact]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transaction
            //Assert.IsType<Transaction>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'ContractId'
        /// </summary>
        [Fact]
        public void ContractIdTest()
        {
            // TODO unit test for the property 'ContractId'
        }
        /// <summary>
        /// Test the property 'ContractAddress'
        /// </summary>
        [Fact]
        public void ContractAddressTest()
        {
            // TODO unit test for the property 'ContractAddress'
        }
        /// <summary>
        /// Test the property 'Blockchain'
        /// </summary>
        [Fact]
        public void BlockchainTest()
        {
            // TODO unit test for the property 'Blockchain'
        }
        /// <summary>
        /// Test the property 'ChainName'
        /// </summary>
        [Fact]
        public void ChainNameTest()
        {
            // TODO unit test for the property 'ChainName'
        }
        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Fact]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'Environment'
        /// </summary>
        [Fact]
        public void EnvironmentTest()
        {
            // TODO unit test for the property 'Environment'
        }
        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Fact]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Fact]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Fact]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Fact]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }

    }

}
