/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using L3vels.Sdk.Model;
using L3vels.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace L3vels.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAssetDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAssetDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAssetDto
        //private UpdateAssetDto instance;

        public UpdateAssetDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateAssetDto
            //instance = new UpdateAssetDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAssetDto
        /// </summary>
        [Fact]
        public void UpdateAssetDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAssetDto
            //Assert.IsType<UpdateAssetDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Supply'
        /// </summary>
        [Fact]
        public void SupplyTest()
        {
            // TODO unit test for the property 'Supply'
        }
        /// <summary>
        /// Test the property 'AssetUrl'
        /// </summary>
        [Fact]
        public void AssetUrlTest()
        {
            // TODO unit test for the property 'AssetUrl'
        }
        /// <summary>
        /// Test the property 'CustomProps'
        /// </summary>
        [Fact]
        public void CustomPropsTest()
        {
            // TODO unit test for the property 'CustomProps'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

    }

}
