/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using L3vels.Sdk.Client;
using L3vels.Sdk.Api;
// uncomment below to import models
//using L3vels.Sdk.Model;

namespace L3vels.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing AssetApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AssetApiTests : IDisposable
    {
        private AssetApi instance;

        public AssetApiTests()
        {
            instance = new AssetApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AssetApi
            //Assert.IsType<AssetApi>(instance);
        }

        /// <summary>
        /// Test CountByGame
        /// </summary>
        [Fact]
        public void CountByGameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string projectId = null;
            //var response = instance.CountByGame(authorization, projectId);
            //Assert.IsType<decimal>(response);
        }

        /// <summary>
        /// Test GetAssetById
        /// </summary>
        [Fact]
        public void GetAssetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string id = null;
            //string projectId = null;
            //var response = instance.GetAssetById(authorization, id, projectId);
            //Assert.IsType<Asset>(response);
        }

        /// <summary>
        /// Test GetAssets
        /// </summary>
        [Fact]
        public void GetAssetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string projectId = null;
            //string collectionId = null;
            //string sort = null;
            //string order = null;
            //string searchText = null;
            //decimal? limit = null;
            //decimal? page = null;
            //var response = instance.GetAssets(authorization, projectId, collectionId, sort, order, searchText, limit, page);
            //Assert.IsType<AssetsResponseDto>(response);
        }

        /// <summary>
        /// Test UpdateAsset
        /// </summary>
        [Fact]
        public void UpdateAssetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string id = null;
            //UpdateAssetDto updateAssetDto = null;
            //var response = instance.UpdateAsset(authorization, id, updateAssetDto);
            //Assert.IsType<Asset>(response);
        }
    }
}
