/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using L3vels.Sdk.Client;
using L3vels.Sdk.Api;

namespace L3vels.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing CollectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CollectionApiTests : IDisposable
    {
        private CollectionApi instance;

        public CollectionApiTests()
        {
            instance = new CollectionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CollectionApi
            //Assert.IsType<CollectionApi>(instance);
        }

        /// <summary>
        /// Test CollectionControllerCollectionById
        /// </summary>
        [Fact]
        public void CollectionControllerCollectionByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string id = null;
            //string projectId = null;
            //var response = instance.CollectionControllerCollectionById(authorization, id, projectId);
            //Assert.IsType<Collection>(response);
        }

        /// <summary>
        /// Test CollectionControllerCollections
        /// </summary>
        [Fact]
        public void CollectionControllerCollectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string projectId = null;
            //string sort = null;
            //string order = null;
            //string searchText = null;
            //decimal? limit = null;
            //decimal? page = null;
            //var response = instance.CollectionControllerCollections(authorization, projectId, sort, order, searchText, limit, page);
            //Assert.IsType<List<Collection>>(response);
        }

        /// <summary>
        /// Test CollectionControllerCollectionsCountByGameId
        /// </summary>
        [Fact]
        public void CollectionControllerCollectionsCountByGameIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string projectId = null;
            //var response = instance.CollectionControllerCollectionsCountByGameId(authorization, projectId);
            //Assert.IsType<decimal>(response);
        }
    }
}
