/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using L3vels.Sdk.Client;
using L3vels.Sdk.Api;
// uncomment below to import models
//using L3vels.Sdk.Model;

namespace L3vels.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing ContractApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ContractApiTests : IDisposable
    {
        private ContractApi instance;

        public ContractApiTests()
        {
            instance = new ContractApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContractApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ContractApi
            //Assert.IsType<ContractApi>(instance);
        }

        /// <summary>
        /// Test ContractControllerCollectionSize
        /// </summary>
        [Fact]
        public void ContractControllerCollectionSizeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string collectionId = null;
            //string projectId = null;
            //instance.ContractControllerCollectionSize(authorization, collectionId, projectId);
        }

        /// <summary>
        /// Test ContractControllerContractUri
        /// </summary>
        [Fact]
        public void ContractControllerContractUriTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //string collectionId = null;
            //string projectId = null;
            //instance.ContractControllerContractUri(authorization, collectionId, projectId);
        }

        /// <summary>
        /// Test ContractControllerSetContractUri
        /// </summary>
        [Fact]
        public void ContractControllerSetContractUriTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //SetContractUriDto setContractUriDto = null;
            //instance.ContractControllerSetContractUri(authorization, setContractUriDto);
        }

        /// <summary>
        /// Test ContractControllerSetSaleStatus
        /// </summary>
        [Fact]
        public void ContractControllerSetSaleStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authorization = null;
            //SetSaleStatusDto setSaleStatusDto = null;
            //instance.ContractControllerSetSaleStatus(authorization, setSaleStatusDto);
        }
    }
}
