/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using L3vels.Sdk.Client;
using L3vels.Sdk.Api;

namespace L3vels.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing UtilitiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UtilitiesApiTests : IDisposable
    {
        private UtilitiesApi instance;

        public UtilitiesApiTests()
        {
            instance = new UtilitiesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UtilitiesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UtilitiesApi
            //Assert.IsType<UtilitiesApi>(instance);
        }

        /// <summary>
        /// Test UtilityControllerHealth
        /// </summary>
        [Fact]
        public void UtilityControllerHealthTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.UtilityControllerHealth();
        }
    }
}
