/*
 * L3vels Api
 *
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = L3vels.Sdk.Client.OpenAPIDateConverter;

namespace L3vels.Sdk.Model
{
    /// <summary>
    /// MintBatchDto
    /// </summary>
    [DataContract(Name = "MintBatchDto")]
    public partial class MintBatchDto : IEquatable<MintBatchDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MintBatchDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MintBatchDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MintBatchDto" /> class.
        /// </summary>
        /// <param name="projectId">Project Id (required).</param>
        /// <param name="collectionId">Collection Id (required).</param>
        /// <param name="playerAddress">Player address to mint token to (required).</param>
        /// <param name="playerId">Player ID to mint to. You can provide this or player_address (required).</param>
        /// <param name="assets">Array of tokens to mint (required).</param>
        public MintBatchDto(string projectId = default(string), string collectionId = default(string), string playerAddress = default(string), string playerId = default(string), List<string> assets = default(List<string>))
        {
            // to ensure "projectId" is required (not null)
            if (projectId == null)
            {
                throw new ArgumentNullException("projectId is a required property for MintBatchDto and cannot be null");
            }
            this.ProjectId = projectId;
            // to ensure "collectionId" is required (not null)
            if (collectionId == null)
            {
                throw new ArgumentNullException("collectionId is a required property for MintBatchDto and cannot be null");
            }
            this.CollectionId = collectionId;
            // to ensure "playerAddress" is required (not null)
            if (playerAddress == null)
            {
                throw new ArgumentNullException("playerAddress is a required property for MintBatchDto and cannot be null");
            }
            this.PlayerAddress = playerAddress;
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new ArgumentNullException("playerId is a required property for MintBatchDto and cannot be null");
            }
            this.PlayerId = playerId;
            // to ensure "assets" is required (not null)
            if (assets == null)
            {
                throw new ArgumentNullException("assets is a required property for MintBatchDto and cannot be null");
            }
            this.Assets = assets;
        }

        /// <summary>
        /// Project Id
        /// </summary>
        /// <value>Project Id</value>
        /// <example>&quot;a44b646a-ae14-4e05-ae09-b12d5e7269bf&quot;</example>
        [DataMember(Name = "project_id", IsRequired = true, EmitDefaultValue = true)]
        public string ProjectId { get; set; }

        /// <summary>
        /// Collection Id
        /// </summary>
        /// <value>Collection Id</value>
        /// <example>&quot;a44b646a-ae14-4e05-ae09-b12d5e7269bf&quot;</example>
        [DataMember(Name = "collection_id", IsRequired = true, EmitDefaultValue = true)]
        public string CollectionId { get; set; }

        /// <summary>
        /// Player address to mint token to
        /// </summary>
        /// <value>Player address to mint token to</value>
        /// <example>&quot;0x0000000000000000000000000000000000000000&quot;</example>
        [DataMember(Name = "player_address", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerAddress { get; set; }

        /// <summary>
        /// Player ID to mint to. You can provide this or player_address
        /// </summary>
        /// <value>Player ID to mint to. You can provide this or player_address</value>
        /// <example>&quot;a44b646a-ae14-4e05-ae09-b12d5e7269bf&quot;</example>
        [DataMember(Name = "player_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Array of tokens to mint
        /// </summary>
        /// <value>Array of tokens to mint</value>
        [DataMember(Name = "assets", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Assets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MintBatchDto {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  PlayerAddress: ").Append(PlayerAddress).Append("\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MintBatchDto);
        }

        /// <summary>
        /// Returns true if MintBatchDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MintBatchDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MintBatchDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProjectId == input.ProjectId ||
                    (this.ProjectId != null &&
                    this.ProjectId.Equals(input.ProjectId))
                ) && 
                (
                    this.CollectionId == input.CollectionId ||
                    (this.CollectionId != null &&
                    this.CollectionId.Equals(input.CollectionId))
                ) && 
                (
                    this.PlayerAddress == input.PlayerAddress ||
                    (this.PlayerAddress != null &&
                    this.PlayerAddress.Equals(input.PlayerAddress))
                ) && 
                (
                    this.PlayerId == input.PlayerId ||
                    (this.PlayerId != null &&
                    this.PlayerId.Equals(input.PlayerId))
                ) && 
                (
                    this.Assets == input.Assets ||
                    this.Assets != null &&
                    input.Assets != null &&
                    this.Assets.SequenceEqual(input.Assets)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProjectId != null)
                {
                    hashCode = (hashCode * 59) + this.ProjectId.GetHashCode();
                }
                if (this.CollectionId != null)
                {
                    hashCode = (hashCode * 59) + this.CollectionId.GetHashCode();
                }
                if (this.PlayerAddress != null)
                {
                    hashCode = (hashCode * 59) + this.PlayerAddress.GetHashCode();
                }
                if (this.PlayerId != null)
                {
                    hashCode = (hashCode * 59) + this.PlayerId.GetHashCode();
                }
                if (this.Assets != null)
                {
                    hashCode = (hashCode * 59) + this.Assets.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
